// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy_7uYIuSvr8wvY12Ibuc1xkTcmkpxp9s',
    appId: '1:411925456327:ios:acc409019aac7f05e6a5e2',
    messagingSenderId: '411925456327',
    projectId: 'restaurant-management-sy-813d3',
    storageBucket: 'restaurant-management-sy-813d3.firebasestorage.app',
    iosBundleId: 'com.example.rmsApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDy_7uYIuSvr8wvY12Ibuc1xkTcmkpxp9s',
    appId: '1:411925456327:ios:acc409019aac7f05e6a5e2',
    messagingSenderId: '411925456327',
    projectId: 'restaurant-management-sy-813d3',
    storageBucket: 'restaurant-management-sy-813d3.firebasestorage.app',
    iosBundleId: 'com.example.rmsApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXlZY5F48GjCzg3bzVth321zX7i3sQfJ0',
    appId: '1:411925456327:web:063f2eae01b80966e6a5e2',
    messagingSenderId: '411925456327',
    projectId: 'restaurant-management-sy-813d3',
    authDomain: 'restaurant-management-sy-813d3.firebaseapp.com',
    storageBucket: 'restaurant-management-sy-813d3.firebasestorage.app',
    measurementId: 'G-70X3MGFMK8',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXlZY5F48GjCzg3bzVth321zX7i3sQfJ0',
    appId: '1:411925456327:web:063f2eae01b80966e6a5e2',
    messagingSenderId: '411925456327',
    projectId: 'restaurant-management-sy-813d3',
    authDomain: 'restaurant-management-sy-813d3.firebaseapp.com',
    storageBucket: 'restaurant-management-sy-813d3.firebasestorage.app',
    measurementId: 'G-70X3MGFMK8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdJp7DmtJ0tITjZUeTuG4lmF0ZyQE8LjY',
    appId: '1:411925456327:android:6c6d81bb2348a8ebe6a5e2',
    messagingSenderId: '411925456327',
    projectId: 'restaurant-management-sy-813d3',
    storageBucket: 'restaurant-management-sy-813d3.firebasestorage.app',
  );

}